name: "Pages"

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/pages.yaml"
      - "docs/**"
      - ".vitepress/**"
      - "package*.json"
  workflow_dispatch:

env:
  CRAWLER_ID: ""

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: "Setup Node 24"
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: "Configure Pages"
        uses: actions/configure-pages@v5

      - name: "Install Dependencies"
        run: |
          npm ci

      - name: "Run Build"
        run: |
          npm run docs:build

      - name: "Upload Pages Artifact"
        uses: actions/upload-pages-artifact@v4
        with:
          path: .vitepress/dist

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Deploy Pages"
        id: deployment
        uses: actions/deploy-pages@v4

      - name: "Send Deploy Notification"
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  post:
    name: "Post-Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: deploy

    steps:
      - name: "Algolia Crawler"
        if: ${{ env.CRAWLER_ID != '' }}
        uses: cssnr/algolia-crawler-action@v1
        with:
          crawler_id: ${{ env.CRAWLER_ID }}
          crawler_user_id: ${{ secrets.CRAWLER_USER_ID }}
          crawler_api_key: ${{ secrets.CRAWLER_API_KEY }}

      - name: "Send Post-Deploy Notification"
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
